### PR TITLE
more info for full ram

### PR DESCRIPTION
**Pull request by ELY3M**
I just saw people asking this.  we better add more info to tell people how to access full ram for this app.

### CODE REVIEW

**Comment by Ninjistix** [comment]
i feel like this can be added to the read me under usage for the switch section, (tbh the readme is kinda outdated also)

**Comment by BernardoGiordano** [comment]
Yeah, this should be explained in the reader rather than into the logs, where it hasn't the same visibility.

**Comment by Nixie722** [comment]
I guess you should add info to hbl, not to every single app that you run through hbl applet mode (since there is limited usage for applet mode). Message is sufficient, if anything, homebrew launcher does not properly explain what is applet mode. 

Also: 
>  `You need to go back to your home screen then press and hold R then tap on one of your games.`
is not enough. Look at gba temp, even with this info people are asking how to run hbl because they are not holding R long enough.

**Comment by Ninjistix** [comment]
I agree with @Nixie722 there's tons of these floating around in the wild https://www.reddit.com/r/SwitchPirates/comments/dgbqs6/checkpoint_homebrew_app/

the whole usage is outdated. no one really reads the change logs or might not understands them.

**Comment by BernardoGiordano** [comment]
Feel free to create a new PR making these changes to the README

**Pull request closed without merging**
